feat: add flag to force hashbrown usage
bluealloy/revm pull request #1284
Opened 2024-04-09 12:19 UTC by Wodann

This allows re-exporting of `hashbrown`, even if the `std` feature flag is enabled.

2024-04-09 23:59 UTC, rakita requested changes
It would be good to propagate this flag to all crates.

2024-04-10 13:21 UTC, Wodann commented
> It would be good to propagate this flag to all crates.

Thanks. Done!

2024-04-11 07:33 UTC, Wodann commented
Could it be that this is a sporadic failure due to it requiring a remote connection?

https://github.com/bluealloy/revm/actions/runs/8632004425/job/23661622655?pr=1284#step:5:132

2024-04-12 16:38 UTC, DaniPopes commented
It's a spurious failure, RPCs like to suck, don't worry about it.

2024-04-12 16:39 UTC, DaniPopes approved these changes

2024-04-13 12:06 UTC, rakita approved these changes

2024-04-13 12:07 UTC, merged