feat: add `Bytecode::original_bytecode_slice` to match `BytecodeLocked`
bluealloy/revm pull request #1286
Opened 2024-04-09 16:35 UTC by DaniPopes

2024-04-09 23:57 UTC, rakita requested changes
`BytecodeLocked` is removed from `main` so this fn needs to be implemented on `Bytecode`

2024-04-12 15:50 UTC, onbjerg approved these changes
lgtm

2024-04-13 12:10 UTC, rakita approved these changes

2024-04-13 12:11 UTC, rakita approved these changes

2024-04-13 12:11 UTC, merged