Implement `with_chain_id` for `CfgEnv`
bluealloy/revm pull request #1327
Opened 2024-04-17 14:52 UTC by tcoratger

2024-04-17 20:36 UTC, mattsse requested changes

2024-04-17 20:36 UTC, mattsse commented on crates/primitives/src/env.rs
> +    pub fn with_chain_id(&self, chain_id: u64) -> Self {
I think this should consume self?

2024-04-18 07:13 UTC, tcoratger commented on crates/primitives/src/env.rs
> +    pub fn with_chain_id(&self, chain_id: u64) -> Self {
fixed

2024-04-18 07:38 UTC, onbjerg approved these changes

2024-04-19 20:43 UTC, DaniPopes approved these changes

2024-04-21 07:21 UTC, rakita approved these changes

2024-04-21 07:21 UTC, merged