refactor: replace U256 to u64 in EIP-2935 BLOCKHASH
bluealloy/revm pull request #1505
Opened 2024-06-11 10:10 UTC by TropicalDog17

## Description

Change the `number` parameter types of `Host` and `Database` `block_hash` method from U256 to u64

Closes #1423

2024-06-11 10:18 UTC, rakita commented on crates/revm/src/context.rs
> +        let requested_number = number as usize;
This can panic. We should use `usize::try_from(number).unwrap_or(usize::MAX);`

2024-06-11 10:20 UTC, rakita requested changes
cool change. One edge case pending

2024-06-11 11:13 UTC, TropicalDog17 commented
@rakita thanks for your review, I've refactored accordingly.

2024-06-11 16:34 UTC, rakita approved these changes
lgtm

2024-06-12 00:09 UTC, DaniPopes approved these changes

2024-06-21 09:47 UTC, merged