feat: add matter-labs based eip1962 precompile impls
bluealloy/revm pull request #1547
Opened 2024-06-18 21:43 UTC by Rjected

This add the EIP 196 precompile implementation based on https://github.com/matter-labs/eip1962 instead of the substrate bn library.

This still needs:
- [ ] extensive testing
- [ ] potentially better error conversions
- [ ] benchmarking for ecMul and pairing precompiles

2024-06-18 22:01 UTC, rakita requested changes
I would want to leave bn behind a feature gate, in case of a need to switch back easily.

2024-06-19 06:54 UTC, DaniPopes commented on crates/precompile/Cargo.toml
> +bn = { package = "substrate-bn", version = "0.6", default-features = false }
looks unused?

2024-07-02 19:38 UTC, Rjected commented
The matter labs repo is not `no_std` compatible, working on it however, so I'll probably need to change from a `bn` feature to a `matter_labs` feature, where matter labs is only selected if std is also available

2025-03-20 10:35 UTC, rakita commented
Cleanup closing, if we go back to it we can always reopen

2025-03-20 10:35 UTC, closed without merging