chore: store tokio::runtime::Handle in ethers/alloyDB
bluealloy/revm pull request #1557
Opened 2024-06-21 00:11 UTC by chirag-bgh

ref #1534

2024-06-21 08:05 UTC, DaniPopes requested changes
can you also return None if the runtime flavor is CurrentThread, and can you document it briefly in the fn new doc comments saying that it requires a tokio runtime?

otherwise looks good

2024-06-21 20:47 UTC, mattsse submitted a review, later dismissed

2024-06-21 20:47 UTC, mattsse commented on crates/revm/src/db/ethersdb.rs
> +    fn block_on<F>(f: F, handle: &Handle) -> F::Output
this function can now accept &self

2024-06-23 23:49 UTC, DaniPopes approved these changes

2024-06-28 11:01 UTC, rakita approved these changes

2024-06-28 11:02 UTC, merged

2024-06-28 12:42 UTC, wtdcode commented
@rakita  This change is not appropriate. If you wish to enforce ethersdb/alloydb to always play with async world, you should mark `fn new` as `async fn new` even not using any `await` in the function. This removes the check and also presents the correct signature.

@DaniPopes I disagree with not allowing ethersdb/alloydb to create current thread runtime. This makes them totally incompatible with sync world and creating a current thread runtime is rather cheap.

2024-06-28 12:55 UTC, wtdcode commented
@DaniPopes Also, why would you disallow the current thread flavor? I can't understand.