Docs fix spelling issues
bluealloy/revm pull request #1715
Opened 2024-08-23 11:08 UTC by nnsW3

Hello
While looking through your docs I found and fixed several spelling issues.
Br, Elias.

2024-08-23 11:11 UTC, onbjerg requested changes

2024-08-23 11:11 UTC, onbjerg commented on documentation/src/crates/primitives/bits.md
> +The code also provides conversions between `B256`, `Address` and various other types such as `u64`, `primitive_types::H256`, `primitive_types::H160`, `primitive_types::U256`, and `ruint::aliases::U25
this is actually incorrect, the blocks being referred to here are code blocks

2024-08-23 11:11 UTC, onbjerg commented on documentation/src/crates/primitives/kzg.md
> +2. `trusted_setup_points`: This module contains functions and types used for parsing and utilizing the [Trusted Setup]( https://ceremony.ethereum.org/) for the `KzgSettings`.
```suggestion
2. `trusted_setup_points`: This module contains functions and types used for parsing and utilizing the [Trusted Setup](https://ceremony.ethereum.org/) for the `KzgSettings`.
```

2024-08-23 11:11 UTC, onbjerg commented on documentation/src/crates/interpreter/memory.md
> +* STATICCALL
not sure what the diff is here?

2024-08-23 11:18 UTC, nnsW3 commented on documentation/src/crates/interpreter/memory.md
> +* STATICCALL
just than with then

2024-08-23 11:18 UTC, nnsW3 commented
done

2024-08-23 11:18 UTC, onbjerg approved these changes

2024-08-26 16:20 UTC, rakita approved these changes
lgtm

2024-08-26 16:20 UTC, merged