feat(interpreter): dispatch using static function array
bluealloy/revm pull request #558
Opened 2023-07-24 14:08 UTC by DaniPopes

Closes #310

2023-07-25 03:12 UTC, DaniPopes reviewed
General changes:
- restrict visibility of items that are not exported to emphasize that they are private
- omit error from `as_usize_or_fail!` macro calls when it's the default (`InvalidOperandOOG`)
- rewrote benches from `revm-test` to criterion, and moved them to `crates/revm/benches/`

2023-07-25 03:12 UTC, DaniPopes commented on crates/interpreter/src/interpreter/stack.rs
Changes:
- `Display` should not be gated to `std`
- use `<[T]>::swap` in `Stack::swap` instead of using pointers and unsafe

2023-07-25 03:12 UTC, DaniPopes commented on crates/interpreter/src/instructions/opcode.rs
Changes:
- declare opcode constants, names (`OPCODE_JUMPMAP`) and the `eval` function in one macro call

2023-07-26 08:08 UTC, DaniPopes commented on crates/interpreter/src/instructions/host.rs
Changes:
- change `is_none()` + `unwrap` to use `let else`

2023-07-31 08:54 UTC, rakita requested changes
@DaniPopes you made too many changes here to be accepted as it is, as I don't agree with some of them

2023-07-31 11:06 UTC, DaniPopes commented
@rakita Sure makes sense, what do you want me to split off / change?

2023-08-03 16:50 UTC, closed without merging