chore: make `impl Default for StateBuilder` generic
bluealloy/revm pull request #690
Opened 2023-09-06 00:52 UTC by DaniPopes

Follow-up to #687, see https://github.com/bluealloy/revm/pull/687#discussion_r1316523492

2023-09-06 09:28 UTC, rakita requested changes
This is more verbose than it was. Using `EmptyDB` removes the need to specify the type for `default()`

2023-09-06 13:56 UTC, DaniPopes commented
This is only true with `StateBuilder`, which can be changed by making the type generic default to `EmptyDB`. But I don't see why `Default` (or other traits in the future) are only implemented for the default type.

2023-09-07 11:25 UTC, rakita commented on crates/revm/src/db/states/state_builder.rs
> +    #[deprecated = "instantiate with `new_with_database` instead"]
I use this fn inside reth, maybe it is not needed as there is `fn with_database` currently in the main, but can you remove `deprecated` for now?

2023-09-07 11:27 UTC, rakita approved these changes
Pending conflicts, but lgtm!

I added  `State::builder()` inside State so `StateBuilder` doesn't need to be specified in usually flows. So we can do `State::builder().build()` pattern.

2023-09-07 22:31 UTC, DaniPopes commented
Re Based

2023-09-07 23:11 UTC, rakita commented on crates/revm/src/db/states/state_builder.rs
> +    /// Set the database. Prefer using [`new_with_database`](Self::new_with_database) when possible.
```suggestion
    /// Set the database.
```

2023-09-07 23:13 UTC, merged