feat: add Stack empty
bluealloy/revm pull request #876
Opened 2023-11-21 19:11 UTC by mattsse

Adds a helper function to get an empty Stack.

this can be beneficial during tracing where stack capturing is optional, and working with `Stack` over `Option<Stack>` is preferred

2023-11-21 23:53 UTC, gakonst approved these changes

2023-11-22 14:16 UTC, rakita commented
cc https://github.com/bluealloy/revm/pull/816 as this stack is going to be overwritten.

2023-11-22 14:16 UTC, rakita approved these changes

2023-11-22 14:21 UTC, rakita requested changes
Wait, this would make functions invalid in Stack as they depend on STACK_LIMIT, so best not to include this.

2023-11-22 14:41 UTC, rakita commented
Additionally, I think you should just clone the stack slice as they have separate purpose that don't overlap, and when a shared stack comes this is going to be needed.

2023-11-22 16:24 UTC, mattsse commented
> Wait, this would make functions invalid in Stack as they depend on STACK_LIMIT, so best not to include this.

ah because the memory operations would be invalid, like ptr based copies?

makes sense, but then this type should not be Clone

2023-11-22 16:28 UTC, closed without merging

2023-11-22 16:28 UTC, gbrew commented
> > Wait, this would make functions invalid in Stack as they depend on STACK_LIMIT, so best not to include this.
> 
> ah because the memory operations would be invalid, like ptr based copies? which require capacity?
> 
> makes sense, but then this type should not be Clone

Yeah, I was just looking at this, and I agree the #[derive(Clone)] on Stack is unsafe, as it won't preserve the invariant that the stack is fully allocated.